### ISSUE TITLE
Extra Points

### ISSUE THREAD

**Issue by danipalli** [htl-perg-2019-20-5ahif/contact-list-exercise-danipalli#1]
Dear Mr. Stropek,

i implemented all technical specifications defined in the swagger.yaml file for earning the extra points.

Do I have to host my Web API somewhere or is uploading my code sufficient?

Kind regards
Daniel

**Comment by rstropek** [comment]
Avoid checking in *bin* folders.

**Comment by rstropek** [comment]
Don't check model manually. Use *data annotations* instead (e.g. [`[Required]`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.dataannotations.requiredattribute?view=netcore-3.0)). Fix that and the extra point is yours.

Greetings,
Rainer Stropek

**Comment by danipalli** [comment]
I updated my solution now and the [Required()] field is working :)

**Comment by rstropek** [comment]
Oh, misunderstanding. The `[Required]` attribute should be on your DTO class properties (e.g. `Person.id`).

**Comment by danipalli** [comment]
Ok, I added the data annotations to my Person class 👍
